import { CLAUDE_API_HEADERS } from "../shared.js";

export default {
  id: "zcode",
  priority: 146,
  alias: "zcode",
  aliases: ["zcode-desktop", "zcode-plan", "zai-zcode"],
  uiAlias: "zcode",
  display: {
    name: "ZCode (Z.ai)",
    icon: "terminal",
    color: "#3B82F6",
    textIcon: "ZCD",
    website: "https://zcode.z.ai",
    notice: {
      apiKeyUrl: "https://zcode.z.ai",
      signupUrl: "https://chat.z.ai",
    },
  },
  category: "oauth",
  authModes: ["oauth", "apikey"],
  hasOAuth: true,
  oauth: {
    providerId: "zai",
    cliInitUrl: "https://zcode.z.ai/api/v1/oauth/cli/init",
    cliPollUrl: "https://zcode.z.ai/api/v1/oauth/cli/poll",
    businessLoginUrl: "https://api.z.ai/api/auth/z/login",
    apiBaseUrl: "https://api.z.ai",
    planApiKeyName: "zcode-api-key",
  },
  authType: "apikey",
  authHint: "Paste your zcodeJwtToken from ZCode or click Login to authenticate via Z.ai CLI OAuth",
  transport: {
    baseUrl: "https://zcode.z.ai/api/v1/zcode-plan/anthropic/v1/messages",
    format: "anthropic",
    authType: "token",
    headers: { ...CLAUDE_API_HEADERS },
  },
  models: [
    { id: "GLM-5.3", name: "GLM-5.3 (ZCode)" },
    { id: "GLM-5.3-Flash", name: "GLM-5.3 Flash (ZCode Start Plan)" },
    { id: "GLM-5.2", name: "GLM-5.2 (ZCode Start Plan)" },
    { id: "GLM-5-Turbo", name: "GLM-5 Turbo (ZCode Start Plan)" },
    { id: "GLM-4.7", name: "GLM-4.7 (ZCode)" },
    { id: "GLM-4.7-Flash", name: "GLM-4.7 Flash (ZCode)" },
    { id: "codegeex-4", name: "CodeGeeX 4 (ZCode)" },
  ],
  serviceKinds: ["llm", "webSearch"],
  passthroughModels: true,
};
